name: HLWM Archive Self-Check

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  check-tars:
    name: Check tarballs
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Importing GPG key
        run: |
          gpg --import gpg-keys.asc

      - name: Running ./check.sh
        run: |
          ./check.sh
